### ISSUE TITLE
api to access metadata from dashboard db should include sample_type

### ISSUE THREAD

**Issue by hsosik** [joefutrelle/pyifcb#56]
If I'm not mistaken, the dashboard database now include a field called something like sample_type (with entries such as underway, cast, underway_discrete, beads), but the export_metadata api (e.g., https://ifcb-data.whoi.edu/api/export_metadata/SPIROPA) does not include that column. For my current use, that info would be very helpful. 

P.S. Not sure if I'm posting this issue in the correct repo...feel free to move it if appropriate.

**Comment by joefutrelle** [comment]
Wrong repo. I'll post this to ifcbdb.
