### ISSUE TITLE
users need api to query counts in class and class_tag combinations from ifcb-annotate database

### ISSUE THREAD

**Issue by hsosik** [joefutrelle/pyifcb#58]
Could we have an api that provides per data set results as counts in a matrix of bin rows and class (and any relevant class-tag combos) columns? 

P.S. Is this the correct repo for this issues?

**Comment by joefutrelle** [comment]
wrong repo, this should be reported in the ifcb annotate repo.

We can't make this an API because it would be so slow that the web request would time out.
