### ISSUE TITLE
Add new ml_analyzed algorithm for certain IFCB5 files

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/pyifcb#67]
The new implementation will live here:

https://github.com/joefutrelle/pyifcb/blob/master/ifcb/metrics/ml_analyzed.py

**Comment by hsosik** [comment]
Currently for all IFCB1 and IFCB5 bins the algorithm uses MIN_PROC_TIME = 0.073. The update is for IFCB5 only and only after June 2015: for those bins MIN_PROC_TIME = 0.050.  IFCB5 bins before June 2015 and all IFCB1 bins should remain unchanged.
